### ISSUE TITLE
After successful commitment still data entered is not reset in bets page

### ISSUE THREAD

**Issue by Pratyushagit1** [DoubleDice-com/live#12]
In bets page
Bet with some amount and wait until it's success
Observe that still entered data for bets is displaying - Not expected
![image (5)](https://user-images.githubusercontent.com/71684692/158792843-6e9681a4-1bed-4075-9a7d-fc9d355fa839.png)

**Comment by aminDaryan** [comment]
Both option selected and bet amount reset now when a bet has been made.
