### ISSUE TITLE
Rounding issue with Weighted Bet field

### ISSUE THREAD

**Issue by Pratyushagit1** [DoubleDice-com/live#13]
Create a bet with fractional multiplier value/ bet with fractional value example 1.251
Observe that Weighted Bet is not showing proper value
![image (6)](https://user-images.githubusercontent.com/71684692/158793509-a2130d35-a1a6-4b09-8da1-0b0ae4e87ffd.png)

From VK: This is the same issue as inputting the rake at 1.33%

**Comment by aminDaryan** [comment]
The weighted bet section is no longer in use and has been removed.
