### ISSUE TITLE
Bet page - After selecting a option from drop down, drop down is not closed automatically

### ISSUE THREAD

**Issue by Pratyushagit1** [DoubleDice-com/live#17]
Create a VF
Go to Room and click on 'Bet On' drop down
Options list is displayed
Select 1 option (example 2nd one)
Option is shown in selected state but drop down is not closed automatically
Still drop down is displayed- **Not expected**
![image](https://user-images.githubusercontent.com/71684692/159491441-24af1c90-0998-42f1-9a6e-73a42f6ec5b6.png)

**Comment by aminDaryan** [comment]
This issue was fixed.
