### ISSUE TITLE
Bet page - Help icon is not displaying with '?'

### ISSUE THREAD

**Issue by Pratyushagit1** [DoubleDice-com/live#18]
Go to bets page
On top right corner beside wallet address help icon is added
Observe that help icon displaying as '1' not '?' - **Not expected**
![image](https://user-images.githubusercontent.com/71684692/159492028-414aa6ce-0c91-4209-bcb0-fac36544a474.png)

**Comment by petermunachi** [comment]
@Pratyushagit1 it show the question mark icon in my browser which is the expected behavior. Please what browser are you using?

**Comment by Pratyushagit1** [comment]
![image](https://user-images.githubusercontent.com/71684692/159873412-16373231-a430-4861-920d-edbd6318adfb.png)

Windows 10 Chrome Browser

**Comment by aminDaryan** [comment]
It was closed as this issue wasnt reported anymore
