### ISSUE TITLE
Bet page - When connected to wallet in Lobby and accessing bet page asking to connect to wallet again

### ISSUE THREAD

**Issue by Pratyushagit1** [DoubleDice-com/live#19]
Create a VF
Navigate to Lobby (connected to wallet)
Click on any Bet available in Lobby
Navigated to Bet page in separate window
Observe that wallet is not connected - Not expected

@petermunachi  going to fix this as Bet page is going to open in same window

**Comment by petermunachi** [comment]
the lobby page now open on same tab, so this issue is resolved
