### ISSUE TITLE
Use same wording as 'Pool' everywhere

### ISSUE THREAD

**Issue by Pratyushagit1** [DoubleDice-com/live#20]
We should use word 'Pool' everywhere
change Pot word to 'Pool' in Lobby page
![image (7)](https://user-images.githubusercontent.com/71684692/159497149-2add8e27-d62a-4c51-b683-1925d29b671c.png)

**Comment by petermunachi** [comment]
this issue have been resolved

**Comment by zduniak** [comment]
@Pratyushagit1 - can you please double check and close if done
