### ISSUE TITLE
Add 'Create Bet' button and navigate to Bet list when clicking on DD logo

### ISSUE THREAD

**Issue by Pratyushagit1** [DoubleDice-com/live#22]
Clicking on 'Double Dice' logo
Current: Taking to Create bet page
Expected: Should navigate to Bet list page

Also in Bet list page add **'Create Bet' button** so that user can create bet from bet list page also

**Comment by petermunachi** [comment]
This issue have been resolved

**Comment by aminDaryan** [comment]
I believe this task is finished.
