### ISSUE TITLE
Site is vibrating

### ISSUE THREAD

**Issue by mz7mz7mz7** [DoubleDice-com/live#23]
Issue reported by Bob on Telegram:
https://share.descript.com/view/BLz1pMZ1EQs

**Comment by mz7mz7mz7** [comment]
Here is a duplicate @brhanegiday of the same issue, with a bit more details and context: https://github.com/DoubleDice-com/beta/issues/24

**Comment by aminDaryan** [comment]
This issue is not being mentioned anymore for some time by any of the users, therefore I will close it.
