### ISSUE TITLE
Unable to create bet page - problem creating discord channel

### ISSUE THREAD

**Issue by waesk** [DoubleDice-com/live#6]
Receive attached error when creating bet page. Time stamp in NZDT
![Problem creating discord channel](https://user-images.githubusercontent.com/7037548/157551299-03b96c14-9c4d-4203-aee1-e39c294fbf12.png)
.

**Comment by vibhandikyash** [comment]
This issue is fixed now. @waesk Would be great if you can test it again and if it works fine we can close it. :D
