### ISSUE TITLE
Not able to visit the bet page after successfully creating a VF

### ISSUE THREAD

**Issue by vibhandikyash** [DoubleDice-com/live#7]
Pl. try to visit the below URL's:

https://beta.doubledice.com/bet/1230392700226027325991830945792
https://beta.doubledice.com/bet/1067328996096714362023906902016

**Comment by aminDaryan** [comment]
@petermunachi I believe this is not front end.

**Comment by petermunachi** [comment]
This issue have been fixed on the new update
