### ISSUE TITLE
Metamask UI Issue

### ISSUE THREAD

**Issue by NonFuddableTurkey** [DoubleDice-com/live#9]
The user interface in IOS mobile app for Metamask is not compatible. Attached are some screenshots. 

![28477253-D434-4D4C-BF89-ECA6A78B6BCC](https://user-images.githubusercontent.com/101363249/157750661-3ae25a7e-2d74-46cd-8c66-c0b52dcf177a.jpeg)

https://user-images.githubusercontent.com/101363249/157750662-3dc11da8-9d85-4cd5-9886-2441aec47735.MP4

**Comment by zduniak** [comment]
Yes, we know that, as we said in the Beta Instructions ( https://link.doubledice.com/beta-instruction ) the app is not yet mobile-responsive. We work on it in parallel. Thanks for your comment @NonFuddableTurkey
